[2022-12-10 20:40:29] ALERT: Rebuild database fault: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'BnzOhX3Ggy'@'%' to database 'BnzOhX3Ggy' in C:\xampp\htdocs\gestimmo1\application\Espo\ORM\Locker\MysqlLocker.php:87 Stack trace: #0 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\Locker\MysqlLocker.php(87): PDO->exec('LOCK TABLES `us...') #1 C:\xampp\htdocs\gestimmo1\application\Espo\Repositories\User.php(102): Espo\ORM\Locker\MysqlLocker->lockExclusive('User') #2 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\Repository\RDBRepository.php(160): Espo\Repositories\User->beforeSave(Object(Espo\Entities\User), Array) #3 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Repositories\Database.php(160): Espo\ORM\Repository\RDBRepository->save(Object(Espo\Entities\User), Array) #4 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\EntityManager.php(264): Espo\Core\Repositories\Database->save(Object(Espo\Entities\User), Array) #5 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\rebuildActions\AddSystemUser.php(55): Espo\ORM\EntityManager->saveEntity(Object(Espo\Entities\User)) #6 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\Schema.php(330): Espo\Core\Utils\Database\Schema\rebuildActions\AddSystemUser->afterRebuild() #7 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\Schema.php(228): Espo\Core\Utils\Database\Schema\Schema->executeRebuildActions('afterRebuild') #8 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\SchemaProxy.php(58): Espo\Core\Utils\Database\Schema\Schema->rebuild() #9 C:\xampp\htdocs\gestimmo1\application\Espo\Core\DataManager.php(145): Espo\Core\Utils\Database\Schema\SchemaProxy->rebuild(NULL) #10 C:\xampp\htdocs\gestimmo1\application\Espo\Core\DataManager.php(110): Espo\Core\DataManager->rebuildDatabase(NULL) #11 C:\xampp\htdocs\gestimmo1\install\core\Installer.php(417): Espo\Core\DataManager->rebuild() #12 C:\xampp\htdocs\gestimmo1\install\core\actions\buildDatabase.php(33): Installer->buildDatabase() #13 C:\xampp\htdocs\gestimmo1\install\entry.php(202): include('C:\\xampp\\htdocs...') #14 C:\xampp\htdocs\gestimmo1\public\install\index.php(32): require_once('C:\\xampp\\htdocs...') #15 {main} [] []
[2022-12-10 20:40:29] ERROR: Uncaught Exception RuntimeException: "System user is not found." at C:\xampp\htdocs\gestimmo1\application\Espo\Core\ApplicationUser.php line 65 {"exception":"[object] (RuntimeException(code: 0): System user is not found. at C:\\xampp\\htdocs\\gestimmo1\\application\\Espo\\Core\\ApplicationUser.php:65)"} []
[2022-12-10 20:40:30] WARNING: E_WARNING: Undefined array key "errors" {"code":2,"message":"Undefined array key \"errors\"","file":"C:\\xampp\\htdocs\\gestimmo1\\install\\vendor\\smarty\\libs\\sysplugins\\smarty_internal_templatebase.php(143) : eval()'d code","line":4} []
[2022-12-10 20:40:30] WARNING: E_WARNING: Attempt to read property "value" on null {"code":2,"message":"Attempt to read property \"value\" on null","file":"C:\\xampp\\htdocs\\gestimmo1\\install\\vendor\\smarty\\libs\\sysplugins\\smarty_internal_templatebase.php(143) : eval()'d code","line":4} []
[2022-12-10 20:48:19] ALERT: Rebuild database fault: PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in C:\xampp\htdocs\gestimmo1\application\Espo\ORM\SqlExecutor.php:70 Stack trace: #0 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\SqlExecutor.php(70): PDO->query('SELECT user.id ...') #1 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\SqlExecutor.php(59): Espo\ORM\SqlExecutor->executeSqlWithDeadlockHandling('SELECT user.id ...', 1) #2 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\Mapper\BaseMapper.php(784): Espo\ORM\SqlExecutor->execute('SELECT user.id ...', false) #3 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\Mapper\BaseMapper.php(108): Espo\ORM\Mapper\BaseMapper->executeSql('SELECT user.id ...') #4 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\Repository\RDBRepository.php(119): Espo\ORM\Mapper\BaseMapper->selectOne(Object(Espo\ORM\Query\Select)) #5 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\EntityManager.php(232): Espo\ORM\Repository\RDBRepository->getById('system') #6 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\rebuildActions\AddSystemUser.php(43): Espo\ORM\EntityManager->getEntity('User', 'system') #7 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\Schema.php(330): Espo\Core\Utils\Database\Schema\rebuildActions\AddSystemUser->afterRebuild() #8 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\Schema.php(228): Espo\Core\Utils\Database\Schema\Schema->executeRebuildActions('afterRebuild') #9 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\SchemaProxy.php(58): Espo\Core\Utils\Database\Schema\Schema->rebuild() #10 C:\xampp\htdocs\gestimmo1\application\Espo\Core\DataManager.php(145): Espo\Core\Utils\Database\Schema\SchemaProxy->rebuild(NULL) #11 C:\xampp\htdocs\gestimmo1\application\Espo\Core\DataManager.php(110): Espo\Core\DataManager->rebuildDatabase(NULL) #12 C:\xampp\htdocs\gestimmo1\install\core\Installer.php(417): Espo\Core\DataManager->rebuild() #13 C:\xampp\htdocs\gestimmo1\install\core\actions\buildDatabase.php(33): Installer->buildDatabase() #14 C:\xampp\htdocs\gestimmo1\install\entry.php(202): include('C:\\xampp\\htdocs...') #15 C:\xampp\htdocs\gestimmo1\public\install\index.php(32): require_once('C:\\xampp\\htdocs...') #16 {main} [] []
[2022-12-10 20:48:19] ERROR: Uncaught Exception PDOException: "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" at C:\xampp\htdocs\gestimmo1\application\Espo\ORM\SqlExecutor.php line 70 {"exception":"[object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 2006 MySQL server has gone away at C:\\xampp\\htdocs\\gestimmo1\\application\\Espo\\ORM\\SqlExecutor.php:70)"} []
[2022-12-10 20:50:33] ERROR: Failed to rebuild database schema. Details: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away at C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Helper.php:413 [] []
[2022-12-10 20:50:33] ERROR: Uncaught Exception PDOException: "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" at C:\xampp\htdocs\gestimmo1\application\Espo\ORM\SqlExecutor.php line 70 {"exception":"[object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 2006 MySQL server has gone away at C:\\xampp\\htdocs\\gestimmo1\\application\\Espo\\ORM\\SqlExecutor.php:70)"} []
[2022-12-10 20:53:05] ALERT: Rebuild database fault: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'BnzOhX3Ggy'@'%' to database 'BnzOhX3Ggy' in C:\xampp\htdocs\gestimmo1\application\Espo\ORM\Locker\MysqlLocker.php:87 Stack trace: #0 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\Locker\MysqlLocker.php(87): PDO->exec('LOCK TABLES `us...') #1 C:\xampp\htdocs\gestimmo1\application\Espo\Repositories\User.php(102): Espo\ORM\Locker\MysqlLocker->lockExclusive('User') #2 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\Repository\RDBRepository.php(160): Espo\Repositories\User->beforeSave(Object(Espo\Entities\User), Array) #3 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Repositories\Database.php(160): Espo\ORM\Repository\RDBRepository->save(Object(Espo\Entities\User), Array) #4 C:\xampp\htdocs\gestimmo1\application\Espo\ORM\EntityManager.php(264): Espo\Core\Repositories\Database->save(Object(Espo\Entities\User), Array) #5 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\rebuildActions\AddSystemUser.php(55): Espo\ORM\EntityManager->saveEntity(Object(Espo\Entities\User)) #6 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\Schema.php(330): Espo\Core\Utils\Database\Schema\rebuildActions\AddSystemUser->afterRebuild() #7 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\Schema.php(228): Espo\Core\Utils\Database\Schema\Schema->executeRebuildActions('afterRebuild') #8 C:\xampp\htdocs\gestimmo1\application\Espo\Core\Utils\Database\Schema\SchemaProxy.php(58): Espo\Core\Utils\Database\Schema\Schema->rebuild() #9 C:\xampp\htdocs\gestimmo1\application\Espo\Core\DataManager.php(145): Espo\Core\Utils\Database\Schema\SchemaProxy->rebuild(NULL) #10 C:\xampp\htdocs\gestimmo1\application\Espo\Core\DataManager.php(110): Espo\Core\DataManager->rebuildDatabase(NULL) #11 C:\xampp\htdocs\gestimmo1\install\core\Installer.php(417): Espo\Core\DataManager->rebuild() #12 C:\xampp\htdocs\gestimmo1\install\core\actions\buildDatabase.php(33): Installer->buildDatabase() #13 C:\xampp\htdocs\gestimmo1\install\entry.php(202): include('C:\\xampp\\htdocs...') #14 C:\xampp\htdocs\gestimmo1\public\install\index.php(32): require_once('C:\\xampp\\htdocs...') #15 {main} [] []
[2022-12-10 20:53:05] ERROR: Uncaught Exception RuntimeException: "System user is not found." at C:\xampp\htdocs\gestimmo1\application\Espo\Core\ApplicationUser.php line 65 {"exception":"[object] (RuntimeException(code: 0): System user is not found. at C:\\xampp\\htdocs\\gestimmo1\\application\\Espo\\Core\\ApplicationUser.php:65)"} []
